spring:
  profiles.active: local
  datasource:
    driver-class-name: ${spring.datasource.driver-class-name}
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# p6Spy ??
# ???? ??? false ? ??? ?!
decorator:
  datasource:
    p6spy:
      enable-logging: true